shortening feedback loop

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -91,23 +91,35 @@ commands:
                   # exit early if any test fails (-failfast only works within a single
                   # package).
                   exit_code=0
-                  pkgs=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
-                  echo "Running $(echo $pkgs | wc -w) packages:"
-                  echo $pkgs
-                  for pkg in $pkgs
-                  do
-                    if ! gotestsum --no-summary=all --jsonfile=jsonfile-${pkg////-} -- $pkg -p 1 -timeout 2h -failfast \
+                  # pkgs=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
+                  # echo "Running $(echo $pkgs | wc -w) packages:"
+                  # echo $pkgs
+                  # for pkg in $pkgs
+                  # do
+                  #   if ! gotestsum --no-summary=all --jsonfile=jsonfile-${pkg////-} -- $pkg -p 1 -timeout 2h -failfast \
+                  #         << parameters.additional-flags >> \
+                  #         ${ENABLE_ENTERPRISE:+-enable-enterprise} \
+                  #         -enable-multi-cluster \
+                  #         -debug-directory="$TEST_RESULTS/debug" \
+                  #         -consul-k8s-image=<< parameters.consul-k8s-image >>
+                  #   then
+                  #     echo "Tests in ${pkg} failed, aborting early"
+                  #     exit_code=1
+                  #     break
+                  #   fi
+                  # done
+                  if ! gotestsum --no-summary=all --jsonfile=jsonfile-${pkg////-} -- ./mesh-gateway -p 1 -timeout 2h -failfast \
                           << parameters.additional-flags >> \
                           ${ENABLE_ENTERPRISE:+-enable-enterprise} \
                           -enable-multi-cluster \
                           -debug-directory="$TEST_RESULTS/debug" \
                           -consul-k8s-image=<< parameters.consul-k8s-image >>
+                          -run ^TestMeshGatewaySecure$
                     then
                       echo "Tests in ${pkg} failed, aborting early"
                       exit_code=1
                       break
                     fi
-                  done
                   gotestsum --raw-command --junitfile "$TEST_RESULTS/gotestsum-report.xml" -- cat jsonfile*
                   exit $exit_code
 
@@ -127,12 +139,13 @@ commands:
 
                   pkgs=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
                   echo "Running $pkgs"
-                  gotestsum --junitfile "$TEST_RESULTS/gotestsum-report.xml" -- $pkgs -p 1 -timeout 2h -failfast \
+                  gotestsum --junitfile "$TEST_RESULTS/gotestsum-report.xml" -- ./mesh-gateway -p 1 -timeout 2h -failfast \
                       << parameters.additional-flags >> \
                       -enable-multi-cluster \
                       ${ENABLE_ENTERPRISE:+-enable-enterprise} \
                       -debug-directory="$TEST_RESULTS/debug" \
                       -consul-k8s-image=<< parameters.consul-k8s-image >>
+                      -run ^TestMeshGatewaySecure$
 
 jobs:
   go-fmt-and-vet-control-plane:
@@ -495,7 +508,7 @@ jobs:
     machine:
       image: ubuntu-2004:202010-01
     resource_class: xlarge
-    parallelism: 6
+    # parallelism: 6
     steps:
       - checkout
       - install-prereqs
@@ -527,7 +540,7 @@ jobs:
     machine:
       image: ubuntu-2004:202010-01
     resource_class: xlarge
-    parallelism: 6
+    # parallelism: 6
     steps:
       - checkout
       - install-prereqs
